name: Build and publish a Docker image to ghcr.io
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-22.04-arm"

    steps:
      - name: Checkout Repo and Submodules
        uses: actions/checkout@v5.0.0
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT_TOKEN }} # otherwise defaults to ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          extra_args: "--platform=linux/arm/v7"
          github_token: ${{ secrets.GITHUB_TOKEN }}
